export type SemanticForegroundColors = {
  // brand
  brandAccent: string
  brandAccentLight: string
  // caution
  caution: string
  cautionLight: string
  // critical
  critical: string
  criticalLight: string
  // form
  formAccent: string
  formAccentLight: string
  // info
  info: string
  infoLight: string
  // link
  link: string
  linkLight: string
  linkHover: string
  linkVisited: string
  linkLightVisited: string
  // neutral
  neutral: string
  neutralInverted: string
  // positive
  positive: string
  positiveLight: string
  // promote
  promote: string
  promoteLight: string
  // rating
  rating: string
  // secondary
  secondary: string
  secondaryInverted: string
}

export type SemanticBackgroundColors = {
  // body
  body: string
  bodyDark: string
  // brand
  brand: string
  brandAccent: string
  brandAccentActive: string
  brandAccentHover: string
  brandAccentSoft: string
  brandAccentSoftHover: string
  // caution
  caution: string
  cautionLight: string
  // critical
  critical: string
  criticalLight: string
  criticalActive: string
  criticalHover: string
  criticalSoft: string
  criticalSoftActive: string
  criticalSoftHover: string
  // form
  formAccentActive: string
  formAccentHover: string
  formAccentSoft: string
  formAccentSoftActive: string
  formAccentSoftHover: string
  // info
  info: string
  infoLight: string
  // neutral
  neutral: string
  neutralActive: string
  neutralHover: string
  neutralLight: string
  neutralSoft: string
  neutralSoftActive: string
  neutralSoftHover: string
  // positive
  positive: string
  positiveLight: string
  // promote
  promote: string
  promoteLight: string
  // surface
  surface: string
  surfaceDark: string
}

export type dd =
  | 'body'
  | 'bodyDark'
  | 'brand'
  | 'brandAccent'
  | 'brandAccentActive'
  | 'brandAccentHover'
  | 'brandAccentSoft'
  | 'brandAccentSoftHover'
  | 'caution'
  | 'cautionLight'
  | 'critical'
  | 'criticalLight'
  | 'criticalActive'
  | 'criticalHover'
  | 'criticalSoft'
  | 'criticalSoftActive'
  | 'criticalSoftHover'
  | 'formAccentActive'
  | 'formAccentHover'
  | 'formAccentSoft'
  | 'formAccentSoftActive'
  | 'formAccentSoftHover'
  | 'info'
  | 'infoLight'
  | 'neutral'
  | 'neutralActive'
  | 'neutralHover'
  | 'neutralLight'
  | 'neutralSoft'
  | 'neutralSoftActive'
  | 'neutralSoftHover'
  | 'positive'
  | 'positiveLight'
  | 'promote'
  | 'promoteLight'
  | 'surface'
  | 'surfaceDark'
