import { createGlobalThemeContract, createGlobalTheme } from '@vanilla-extract/css'
import * as r from '@radix-ui/colors'

const lightColors = {
  hiContrast: r.slate.slate12,
  loContrast: 'white',
  canvas: 'hsl(0 0% 93%)',
  panel: 'white',
  transparentPanel: 'hsl(0 0% 0% / 97%)',
  shadowLight: 'hsl(206 22% 7% / 35%)',
  shadowDark: 'hsl(206 22% 7% / 20%)',
  bgPrimary: r.slate.slate2,
  bgSecondary: r.slate.slate1,
  bgDimmed: r.slate.slate3,
  textPrimary: r.slate.slate11,
  textSecondary: r.slate.slate12,
  textDimmed: r.slate.slate10,
  ...r.amber,
  // ...r.amberA,
  ...r.blackA,
  ...r.blue,
  // ...r.blueA,
  ...r.brown,
  // ...r.brownA,
  ...r.bronze,
  // ...r.bronzeA,
  ...r.crimson,
  // ...r.crimsonA,
  ...r.cyan,
  // ...r.cyanA,
  ...r.gold,
  // ...r.goldA,
  ...r.grass,
  // ...r.grassA,
  ...r.gray,
  // ...r.grayA,
  ...r.green,
  // ...r.greenA,
  ...r.indigo,
  // ...r.indigoA,
  ...r.lime,
  // ...r.limeA,
  ...r.mauve,
  // ...r.mauveA,
  ...r.mint,
  // ...r.mintA,
  ...r.olive,
  // ...r.oliveA,
  ...r.orange,
  // ...r.orangeA,
  ...r.pink,
  // ...r.pinkA,
  ...r.plum,
  // ...r.plumA,
  ...r.purple,
  // ...r.purpleA,
  ...r.red,
  // ...r.redA,
  ...r.sage,
  // ...r.sageA,
  ...r.sand,
  // ...r.sandA,
  ...r.sky,
  // ...r.skyA,
  ...r.slate,
  // ...r.slateA,
  ...r.teal,
  // ...r.tealA,
  ...r.tomato,
  // ...r.tomatoA,
  ...r.whiteA,
  ...r.violet,
  // ...r.violetA,
  ...r.yellow
  // ...r.yellowA
}

const darkColors = {
  hiContrast: r.slateDark.slate12,
  loContrast: r.slateDark.slate1,
  canvas: 'hsl(0 0% 15%)',
  panel: r.slateDark.slate3,
  transparentPanel: 'hsl(0 100% 100% / 97%)',
  shadowLight: 'hsl(206 22% 7% / 35%)',
  shadowDark: 'hsl(206 22% 7% / 20%)',
  bgPrimary: r.slateDark.slate2,
  bgSecondary: r.slateDark.slate1,
  bgDimmed: r.slateDark.slate3,
  textPrimary: r.slateDark.slate11,
  textSecondary: r.slateDark.slate12,
  textDimmed: r.slateDark.slate10,
  ...r.amberDark,
  // ...r.amberDarkA,
  ...r.blackA,
  ...r.blueDark,
  // ...r.blueDarkA,
  ...r.brownDark,
  // ...r.brownDarkA,
  ...r.bronzeDark,
  // ...r.bronzeDarkA,
  ...r.crimsonDark,
  // ...r.crimsonDarkA,
  ...r.cyanDark,
  // ...r.cyanDarkA,
  ...r.goldDark,
  // ...r.goldDarkA,
  ...r.grassDark,
  // ...r.grassDarkA,
  ...r.grayDark,
  // ...r.grayDarkA,
  ...r.greenDark,
  // ...r.greenDarkA,
  ...r.indigoDark,
  // ...r.indigoDarkA,
  ...r.limeDark,
  // ...r.limeDarkA,
  ...r.mauveDark,
  // ...r.mauveDarkA,
  ...r.mintDark,
  // ...r.mintDarkA,
  ...r.oliveDark,
  // ...r.oliveDarkA,
  ...r.orangeDark,
  // ...r.orangeDarkA,
  ...r.pinkDark,
  // ...r.pinkDarkA,
  ...r.plumDark,
  // ...r.plumDarkA,
  ...r.purpleDark,
  // ...r.purpleDarkA,
  ...r.redDark,
  // ...r.redDarkA,
  ...r.sageDark,
  // ...r.sageDarkA,
  ...r.sandDark,
  // ...r.sandDarkA,
  ...r.skyDark,
  // ...r.skyDarkA,
  ...r.slateDark,
  // ...r.slateDarkA,
  ...r.tealDark,
  // ...r.tealDarkA,
  ...r.tomatoDark,
  // ...r.tomatoDarkA,
  ...r.whiteA,
  ...r.violetDark,
  // ...r.violetDarkA,
  ...r.yellowDark
  // ...r.yellowDarkA
}

export const colors = createGlobalTheme('[data-theme="light"]', lightColors)

createGlobalTheme('[data-theme="dark"]', colors, darkColors)
