import { createThemeContract, createTheme } from '@vanilla-extract/css'
import * as r from '@radix-ui/colors'
import { NullableTokens } from '@vanilla-extract/css/dist/declarations/src/types'

const createBlankTheme = (obj: { [key: string]: string }): NullableTokens =>
  Object.keys(obj).reduce(
    (acc, key) => ({
      ...acc,
      [key]: null
    }),
    {} as { [key: string]: null }
  )

export const colors = createThemeContract({
  hiContrast: null,
  loContrast: null,
  canvas: null,
  panel: null,
  transparentPanel: null,
  shadowLight: null,
  shadowDark: null,
  bg: {
    primary: null,
    secondary: null,
    dimmed: null
  },
  text: {
    primary: null,
    secondary: null,
    dimmed: null
  },
  amber: createBlankTheme(r.amber),
  amberA: createBlankTheme(r.amberA),
  blackA: createBlankTheme(r.blackA),
  brown: createBlankTheme(r.brown),
  brownA: createBlankTheme(r.brownA),
  bronze: createBlankTheme(r.bronze),
  bronzeA: createBlankTheme(r.bronzeA),
  crimson: createBlankTheme(r.crimson),
  crimsonA: createBlankTheme(r.crimsonA),
  cyan: createBlankTheme(r.cyan),
  cyanA: createBlankTheme(r.cyanA),
  gold: createBlankTheme(r.gold),
  goldA: createBlankTheme(r.goldA),
  grass: createBlankTheme(r.grass),
  grassA: createBlankTheme(r.grassA),
  gray: createBlankTheme(r.gray),
  grayA: createBlankTheme(r.grayA),
  green: createBlankTheme(r.green),
  greenA: createBlankTheme(r.greenA),
  indigo: createBlankTheme(r.indigo),
  indigoA: createBlankTheme(r.indigoA),
  lime: createBlankTheme(r.lime),
  limeA: createBlankTheme(r.limeA),
  mauve: createBlankTheme(r.mauve),
  mauveA: createBlankTheme(r.mauveA),
  mint: createBlankTheme(r.mint),
  mintA: createBlankTheme(r.mintA),
  olive: createBlankTheme(r.olive),
  oliveA: createBlankTheme(r.oliveA),
  orange: createBlankTheme(r.orange),
  orangeA: createBlankTheme(r.orangeA),
  pink: createBlankTheme(r.pink),
  pinkA: createBlankTheme(r.pinkA),
  plum: createBlankTheme(r.plum),
  plumA: createBlankTheme(r.plumA),
  purple: createBlankTheme(r.purple),
  purpleA: createBlankTheme(r.purpleA),
  red: createBlankTheme(r.red),
  redA: createBlankTheme(r.redA),
  sage: createBlankTheme(r.sage),
  sageA: createBlankTheme(r.sageA),
  sand: createBlankTheme(r.sand),
  sandA: createBlankTheme(r.sandA),
  sky: createBlankTheme(r.sky),
  skyA: createBlankTheme(r.skyA),
  slate: createBlankTheme(r.slate),
  slateA: createBlankTheme(r.slateA),
  teal: createBlankTheme(r.teal),
  tealA: createBlankTheme(r.tealA),
  tomato: createBlankTheme(r.tomato),
  tomatoA: createBlankTheme(r.tomatoA),
  whiteA: createBlankTheme(r.whiteA),
  violet: createBlankTheme(r.violet),
  violetA: createBlankTheme(r.violetA),
  yellow: createBlankTheme(r.yellow),
  yellowA: createBlankTheme(r.yellowA)
})

export const lightTheme = createTheme(colors, {
  hiContrast: r.slate.slate12,
  loContrast: 'white',
  canvas: 'hsl(0 0% 93%)',
  panel: 'white',
  transparentPanel: 'hsl(0 0% 0% / 97%)',
  shadowLight: 'hsl(206 22% 7% / 35%)',
  shadowDark: 'hsl(206 22% 7% / 20%)',
  bg: {
    primary: r.slate.slate2,
    secondary: r.slate.slate1,
    dimmed: r.slate.slate3
  },
  text: {
    primary: r.slate.slate11,
    secondary: r.slate.slate12,
    dimmed: r.slate.slate10
  },
  amber: r.amber,
  amberA: r.amberA,
  blackA: r.blackA,
  brown: r.brown,
  brownA: r.brownA,
  bronze: r.bronze,
  bronzeA: r.bronzeA,
  crimson: r.crimson,
  crimsonA: r.crimsonA,
  cyan: r.cyan,
  cyanA: r.cyanA,
  gold: r.gold,
  goldA: r.goldA,
  grass: r.grass,
  grassA: r.grassA,
  gray: r.gray,
  grayA: r.grayA,
  green: r.green,
  greenA: r.greenA,
  indigo: r.indigo,
  indigoA: r.indigoA,
  lime: r.lime,
  limeA: r.limeA,
  mauve: r.mauve,
  mauveA: r.mauveA,
  mint: r.mint,
  mintA: r.mintA,
  olive: r.olive,
  oliveA: r.oliveA,
  orange: r.orange,
  orangeA: r.orangeA,
  pink: r.pink,
  pinkA: r.pinkA,
  plum: r.plum,
  plumA: r.plumA,
  purple: r.purple,
  purpleA: r.purpleA,
  red: r.red,
  redA: r.redA,
  sage: r.sage,
  sageA: r.sageA,
  sand: r.sand,
  sandA: r.sandA,
  sky: r.sky,
  skyA: r.skyA,
  slate: r.slate,
  slateA: r.slateA,
  teal: r.teal,
  tealA: r.tealA,
  tomato: r.tomato,
  tomatoA: r.tomatoA,
  whiteA: r.whiteA,
  violet: r.violet,
  violetA: r.violetA,
  yellow: r.yellow,
  yellowA: r.yellowA
})

export const darkTheme = createTheme(colors, {
  hiContrast: r.slateDark.slate12,
  loContrast: r.slateDark.slate1,
  canvas: 'hsl(0 0% 15%)',
  panel: r.slateDark.slate3,
  transparentPanel: 'hsl(0 100% 100% / 97%)',
  shadowLight: 'hsl(206 22% 7% / 35%)',
  shadowDark: 'hsl(206 22% 7% / 20%)',
  bg: {
    primary: r.slateDark.slate2,
    secondary: r.slateDark.slate1,
    dimmed: r.slateDark.slate3
  },
  text: {
    primary: r.slateDark.slate11,
    secondary: r.slateDark.slate12,
    dimmed: r.slateDark.slate10
  },
  amber: r.amberDark,
  amberA: r.amberDarkA,
  blackA: r.blackA,
  brown: r.brownDark,
  brownA: r.brownDarkA,
  bronze: r.bronzeDark,
  bronzeA: r.bronzeDarkA,
  crimson: r.crimsonDark,
  crimsonA: r.crimsonDarkA,
  cyan: r.cyanDark,
  cyanA: r.cyanDarkA,
  gold: r.goldDark,
  goldA: r.goldDarkA,
  grass: r.grassDark,
  grassA: r.grassDarkA,
  gray: r.grayDark,
  grayA: r.grayDarkA,
  green: r.greenDark,
  greenA: r.greenDarkA,
  indigo: r.indigoDark,
  indigoA: r.indigoDarkA,
  lime: r.limeDark,
  limeA: r.limeDarkA,
  mauve: r.mauveDark,
  mauveA: r.mauveDarkA,
  mint: r.mintDark,
  mintA: r.mintDarkA,
  olive: r.oliveDark,
  oliveA: r.oliveDarkA,
  orange: r.orangeDark,
  orangeA: r.orangeDarkA,
  pink: r.pinkDark,
  pinkA: r.pinkDarkA,
  plum: r.plumDark,
  plumA: r.plumDarkA,
  purple: r.purpleDark,
  purpleA: r.purpleDarkA,
  red: r.redDark,
  redA: r.redDarkA,
  sage: r.sageDark,
  sageA: r.sageDarkA,
  sand: r.sandDark,
  sandA: r.sandDarkA,
  sky: r.skyDark,
  skyA: r.skyDarkA,
  slate: r.slateDark,
  slateA: r.slateDarkA,
  teal: r.tealDark,
  tealA: r.tealDarkA,
  tomato: r.tomatoDark,
  tomatoA: r.tomatoDarkA,
  whiteA: r.whiteA,
  violet: r.violetDark,
  violetA: r.violetDarkA,
  yellow: r.yellowDark,
  yellowA: r.yellowDarkA
})
